const IMAGE_PREDICT_ALT_MIN_RATE = 0.9;
const IMAGE_PREDICT_ALT_MIN_WORD = 5;
const IMAGE_PREDICT_LONGDESC_MIN_RATE = 0.7;
const IMAGE_PREDICT_LONGDESC_MIN_WORD = 15;
const MAX_DETECT_TEXT_LENGTH = 250;

module.exports = {
	IMAGE_PREDICT_ALT_MIN_RATE: IMAGE_PREDICT_ALT_MIN_RATE,
	IMAGE_PREDICT_ALT_MIN_WORD: IMAGE_PREDICT_ALT_MIN_WORD,
	IMAGE_PREDICT_LONGDESC_MIN_RATE: IMAGE_PREDICT_LONGDESC_MIN_RATE,
	IMAGE_PREDICT_LONGDESC_MIN_WORD: IMAGE_PREDICT_LONGDESC_MIN_WORD,
	MAX_DETECT_TEXT_LENGTH: MAX_DETECT_TEXT_LENGTH,
};